name: CI Python con UV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Cambiamos a v4.2.2 o superior (ya compila nativo con nodos actuales)
      - uses: actions/checkout@v4.2.2
      
      # 2. Cambiamos a la v5 de setup-uv, que ya apunta de forma nativa a Node 24
      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Sincronizar entorno
        run: uv sync --frozen
          
      - name: Ejecutar Tests
        run: uv run pytest